In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('../US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data_dropped = accidents_data[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'State', 'Number', 'Street', 'Description']]
accidents_data_dropped.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [4]:
accidents_data_dropped.rename(columns={"Start_Time": "Date/Time", "Start_Lat": "Latitude", "Start_Lng": "Longitude"}, errors="raise", inplace=True)
accidents_data_dropped.head()

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [5]:
michigan_df = accidents_data_dropped.loc[accidents_data_dropped['State'] == "MI"]
michigan_df

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
18,2,2020-12-10 13:29:00,42.501929,-82.918056,Saint Clair Shores,MI,NaN,I-94 W,Incident on I-94 WB near I-696 Drive with caut...
29,2,2019-11-25 07:11:55,43.220390,-85.500961,Cedar Springs,MI,13999.0,Stout Ave NE,Accident on 17 Mile Rd at Stout Ave.
51,2,2020-05-12 18:27:50,42.972679,-85.677254,Grand Rapids,MI,NaN,US-131 S,Center right lane blocked due to accident on U...
60,2,2018-11-05 11:50:26,43.005009,-83.684975,Flint,MI,1620.0,S Grand Traverse St,Accident on Grand Traverse St at Church St.
61,2,2018-09-21 04:49:14,42.967983,-85.683899,Grand Rapids,MI,628.0,Jackson St NW,Accident on Lexington Ave around Jackson St.
...,...,...,...,...,...,...,...,...,...
2906517,2,2017-03-01 17:46:48,42.365290,-83.056190,Detroit,MI,NaN,E Ferry St,Ramp to I-94/Edsel Ford Fwy - Accident.
2906548,2,2018-10-01 19:28:44,42.204420,-83.232920,Taylor,MI,NaN,Detroit Toledo Expy N,At Allen Rd/Exit 37 - Accident. Right lane blo...
2906562,3,2017-01-17 17:32:01,42.359558,-83.436134,Plymouth,MI,NaN,I-275 S,Queueing traffic right lane blocked and right ...
2906574,2,2017-12-21 15:04:47,42.406314,-82.956239,Detroit,MI,NaN,I-94 W,At Outer Dr/Exit 222 - Accident. Right lane bl...
2906591,4,2020-12-24 08:23:00,41.785073,-86.139762,Niles,MI,29612.0,US Highway 12,Incident on US-12 EB near BRUSH RD Road closed...

In [6]:
michigan_df = michigan_df.round(decimals=4)
michigan_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
18,2,2020-12-10 13:29:00,42.5019,-82.9181,Saint Clair Shores,MI,NaN,I-94 W,Incident on I-94 WB near I-696 Drive with caut...
29,2,2019-11-25 07:11:55,43.2204,-85.5010,Cedar Springs,MI,13999.0,Stout Ave NE,Accident on 17 Mile Rd at Stout Ave.
51,2,2020-05-12 18:27:50,42.9727,-85.6773,Grand Rapids,MI,NaN,US-131 S,Center right lane blocked due to accident on U...
60,2,2018-11-05 11:50:26,43.0050,-83.6850,Flint,MI,1620.0,S Grand Traverse St,Accident on Grand Traverse St at Church St.
61,2,2018-09-21 04:49:14,42.9680,-85.6839,Grand Rapids,MI,628.0,Jackson St NW,Accident on Lexington Ave around Jackson St.

In [7]:
michigan_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 67073 entries, 18 to 2906591
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Severity     67073 non-null  int64
 1   Date/Time    67073 non-null  object
 2   Latitude     67073 non-null  float64
 3   Longitude    67073 non-null  float64
 4   City         67073 non-null  object
 5   State        67073 non-null  object
 6   Number       25025 non-null  float64
 7   Street       67073 non-null  object
 8   Description  67073 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 5.1+ MB

In [8]:
michigan_df['Number'] = michigan_df['Number'].fillna(0)

In [9]:
michigan_df['Number'] = michigan_df['Number'].map("{:.0f}".format)

In [10]:
michigan_df['Number'].replace({"0": ""}, inplace=True)

In [11]:
michigan_df.to_csv('../State_csv_files/Michigan.csv', encoding='UTF-8', index=False)