In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('../US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data_dropped = accidents_data[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'State', 'Number', 'Street', 'Description']]
accidents_data_dropped.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [4]:
accidents_data_dropped.rename(columns={"Start_Time": "Date/Time", "Start_Lat": "Latitude", "Start_Lng": "Longitude"}, errors="raise", inplace=True)
accidents_data_dropped.head()

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [5]:
montana_df = accidents_data_dropped.loc[accidents_data_dropped['State'] == "MT"]
montana_df

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
1501,2,2020-12-12 00:26:02,45.696405,-111.185458,Bozeman,MT,1752.0,Jackrabbit Ln,Incident on JACKRABBIT LN near BAXTER LN Drive...
1795,2,2020-12-11 15:26:02.000000000,48.114346,-114.600960,Kila,MT,7399.0,US Highway 2 W,Incident on IDAHO HILL RD near US-2 Drive with...
2657,2,2020-12-24 21:55:40,48.240368,-114.320343,Kalispell,MT,748.0,W Reserve Dr,Incident on RESERVE DR near COUNTRY WAY Drive ...
3480,2,2020-10-22 15:17:30,45.655708,-110.849377,Bozeman,MT,NaN,I-90 E,Stationary traffic on I-90 from Trail Creek Rd...
3747,2,2020-10-25 01:31:30,45.770536,-108.486878,Billings,MT,NaN,I-90 E,Slow traffic on I-90 from MT-3/S 27th St/Exit ...
...,...,...,...,...,...,...,...,...,...
2904043,2,2020-12-06 23:03:04,46.635332,-114.580189,Lolo,MT,44995.0,Lolo Creek Rd,Incident on ELK MEADOWS RD near US-12 Drive wi...
2904825,2,2020-12-04 01:03:08,45.608049,-108.797821,Joliet,MT,4971.0,US Highway 310,Incident on US-310 near WHITE HORSE BENCH Driv...
2904989,2,2020-12-02 02:16:28,45.703139,-110.463752,Livingston,MT,NaN,I-90 E,Incident on I-90 EB near MM 340 Drive with cau...
2905316,2,2020-10-30 23:40:18,45.771522,-111.205912,Belgrade,MT,5787.0,Thorpe Rd,Incident on THORPE RD near AMSTERDAM RD Expect...
2905763,2,2020-10-24 22:28:00,45.680133,-108.715027,Laurel,MT,NaN,I-90 W,Slow traffic on I-90 from I-90/Exit 437 (I-90)...

In [6]:
montana_df = montana_df.round(decimals=4)
montana_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
1501,2,2020-12-12 00:26:02,45.6964,-111.1855,Bozeman,MT,1752.0,Jackrabbit Ln,Incident on JACKRABBIT LN near BAXTER LN Drive...
1795,2,2020-12-11 15:26:02.000000000,48.1143,-114.6010,Kila,MT,7399.0,US Highway 2 W,Incident on IDAHO HILL RD near US-2 Drive with...
2657,2,2020-12-24 21:55:40,48.2404,-114.3203,Kalispell,MT,748.0,W Reserve Dr,Incident on RESERVE DR near COUNTRY WAY Drive ...
3480,2,2020-10-22 15:17:30,45.6557,-110.8494,Bozeman,MT,NaN,I-90 E,Stationary traffic on I-90 from Trail Creek Rd...
3747,2,2020-10-25 01:31:30,45.7705,-108.4869,Billings,MT,NaN,I-90 E,Slow traffic on I-90 from MT-3/S 27th St/Exit ...

In [7]:
montana_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3333 entries, 1501 to 2905763
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Severity     3333 non-null   int64
 1   Date/Time    3333 non-null   object
 2   Latitude     3333 non-null   float64
 3   Longitude    3333 non-null   float64
 4   City         3333 non-null   object
 5   State        3333 non-null   object
 6   Number       1781 non-null   float64
 7   Street       3333 non-null   object
 8   Description  3333 non-null   object
dtypes: float64(3), int64(1), object(5)
memory usage: 260.4+ KB

In [8]:
montana_df['Number'] = montana_df['Number'].fillna(0)

In [9]:
montana_df['Number'] = montana_df['Number'].map("{:.0f}".format)

In [10]:
montana_df['Number'].replace({"0": ""}, inplace=True)

In [11]:
montana_df.reset_index(drop=True, inplace=True)
montana_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2020-12-12 00:26:02,45.6964,-111.1855,Bozeman,MT,1752,Jackrabbit Ln,Incident on JACKRABBIT LN near BAXTER LN Drive...
1,2,2020-12-11 15:26:02.000000000,48.1143,-114.6010,Kila,MT,7399,US Highway 2 W,Incident on IDAHO HILL RD near US-2 Drive with...
2,2,2020-12-24 21:55:40,48.2404,-114.3203,Kalispell,MT,748,W Reserve Dr,Incident on RESERVE DR near COUNTRY WAY Drive ...
3,2,2020-10-22 15:17:30,45.6557,-110.8494,Bozeman,MT,,I-90 E,Stationary traffic on I-90 from Trail Creek Rd...
4,2,2020-10-25 01:31:30,45.7705,-108.4869,Billings,MT,,I-90 E,Slow traffic on I-90 from MT-3/S 27th St/Exit ...

In [12]:
montana_df.to_csv('../State_csv_files/Montana.csv', encoding='UTF-8', index=False)