In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import json
import geojson

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data['Severity'].value_counts()

2    2129263
3     629452
4     119144
1      28751
Name: Severity, dtype: int64

In [5]:
new = accidents_data.loc[(accidents_data['State'] == 'TX')]
new

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
12,A-13,2,2018-04-19 12:48:57,2018-04-19 18:48:57,32.866930,-96.666170,32.861560,-96.657690,0.616,At Northwest Hwy/Exit 11 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
15,A-16,2,2019-04-11 16:35:14,2019-04-11 18:59:25,29.723339,-95.497337,29.723339,-95.497337,0.000,Accident on Westpark Dr at 14th St.,...,False,False,False,False,True,False,Day,Day,Day,Day
22,A-23,2,2018-02-15 10:59:40,2018-02-15 11:29:21,29.640491,-95.482445,29.640491,-95.482445,0.000,Accident on Chimney Rock Rd at US-90 Alt Main St.,...,False,False,False,False,True,False,Day,Day,Day,Day
27,A-28,2,2018-12-21 13:31:29,2018-12-21 14:01:20,30.426109,-97.753906,30.426109,-97.753906,0.000,Accident on Research Blvd Southbound at Pavili...,...,False,False,False,False,False,False,Day,Day,Day,Day
44,A-45,2,2020-01-06 15:37:19,2020-01-06 16:05:57,32.758400,-97.257630,32.759490,-97.248370,0.543,At Brentwood Stair Rd/Exit 19 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2906543,A-2906544,2,2019-12-24 15:51:11,2019-12-24 16:50:58,31.781967,-106.407211,31.781967,-106.407211,0.000,Accident on Geronimo Dr at Gateway Blvd.,...,False,False,False,False,True,False,Day,Day,Day,Day
2906553,A-2906554,2,2019-04-24 06:40:21,2019-04-24 07:38:32,32.752640,-96.770561,32.752640,-96.770561,0.000,Accident on Julius Schepps Fwy Southbound at L...,...,False,False,False,False,False,False,Night,Day,Day,Day
2906557,A-2906558,2,2018-08-01 10:44:19,2018-08-01 11:43:57,32.785675,-96.918732,32.785675,-96.918732,0.000,Accident on TX-12 Loop Southbound at the Trini...,...,False,False,False,False,False,False,Day,Day,Day,Day
2906602,A-2906603,2,2020-10-31 03:49:00,2020-10-31 05:28:04,30.420856,-97.624067,30.419275,-97.620554,0.236,Incident on RENDOVA LN near TRINIDAD LN Drive ...,...,False,False,False,False,False,False,Night,Night,Night,Night
2906605,A-2906606,2,2018-06-28 08:49:01,2018-06-28 09:18:51,29.813824,-95.399437,29.813824,-95.399437,0.000,Accident on 30th St at Yale St.,...,False,False,True,False,False,False,Day,Day,Day,Day

In [6]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 226640 entries, 12 to 2906605
Data columns (total 47 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     226640 non-null  object
 1   Severity               226640 non-null  int64
 2   Start_Time             226640 non-null  object
 3   End_Time               226640 non-null  object
 4   Start_Lat              226640 non-null  float64
 5   Start_Lng              226640 non-null  float64
 6   End_Lat                200483 non-null  float64
 7   End_Lng                200483 non-null  float64
 8   Distance(mi)           226640 non-null  float64
 9   Description            226640 non-null  object
 10  Number                 86878 non-null   float64
 11  Street                 226640 non-null  object
 12  Side                   226640 non-null  object
 13  City                   226640 non-null  object
 14  County                 226640 non-null  object
 15  State                  226640 non-null  object
 16  Zipcode                226640 non-null  object
 17  Country                226640 non-null  object
 18  Timezone               226619 non-null  object
 19  Airport_Code           226614 non-null  object
 20  Weather_Timestamp      223266 non-null  object
 21  Temperature(F)         222428 non-null  float64
 22  Wind_Chill(F)          98691 non-null   float64
 23  Humidity(%)            222074 non-null  float64
 24  Pressure(in)           222588 non-null  float64
 25  Visibility(mi)         221908 non-null  float64
 26  Wind_Direction         222643 non-null  object
 27  Wind_Speed(mph)        204762 non-null  float64
 28  Precipitation(in)      96511 non-null   float64
 29  Weather_Condition      221867 non-null  object
 30  Amenity                226640 non-null  bool
 31  Bump                   226640 non-null  bool
 32  Crossing               226640 non-null  bool
 33  Give_Way               226640 non-null  bool
 34  Junction               226640 non-null  bool
 35  No_Exit                226640 non-null  bool
 36  Railway                226640 non-null  bool
 37  Roundabout             226640 non-null  bool
 38  Station                226640 non-null  bool
 39  Stop                   226640 non-null  bool
 40  Traffic_Calming        226640 non-null  bool
 41  Traffic_Signal         226640 non-null  bool
 42  Turning_Loop           226640 non-null  bool
 43  Sunrise_Sunset         226640 non-null  object
 44  Civil_Twilight         226640 non-null  object
 45  Nautical_Twilight      226640 non-null  object
 46  Astronomical_Twilight  226640 non-null  object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 63.3+ MB

In [7]:
new['Number'] = new['Number'].fillna(0)

C:\Users\frost\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [8]:
new['Number'] = new['Number'].map("{:.0f}".format)
# pd.options.display.float_format = '{:,.0f}'.format
# df['C'] = df['C'].apply(np.int64)

C:\Users\frost\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 226640 entries, 12 to 2906605
Data columns (total 47 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     226640 non-null  object
 1   Severity               226640 non-null  int64
 2   Start_Time             226640 non-null  object
 3   End_Time               226640 non-null  object
 4   Start_Lat              226640 non-null  float64
 5   Start_Lng              226640 non-null  float64
 6   End_Lat                200483 non-null  float64
 7   End_Lng                200483 non-null  float64
 8   Distance(mi)           226640 non-null  float64
 9   Description            226640 non-null  object
 10  Number                 226640 non-null  object
 11  Street                 226640 non-null  object
 12  Side                   226640 non-null  object
 13  City                   226640 non-null  object
 14  County                 226640 non-null  object
 15  State                  226640 non-null  object
 16  Zipcode                226640 non-null  object
 17  Country                226640 non-null  object
 18  Timezone               226619 non-null  object
 19  Airport_Code           226614 non-null  object
 20  Weather_Timestamp      223266 non-null  object
 21  Temperature(F)         222428 non-null  float64
 22  Wind_Chill(F)          98691 non-null   float64
 23  Humidity(%)            222074 non-null  float64
 24  Pressure(in)           222588 non-null  float64
 25  Visibility(mi)         221908 non-null  float64
 26  Wind_Direction         222643 non-null  object
 27  Wind_Speed(mph)        204762 non-null  float64
 28  Precipitation(in)      96511 non-null   float64
 29  Weather_Condition      221867 non-null  object
 30  Amenity                226640 non-null  bool
 31  Bump                   226640 non-null  bool
 32  Crossing               226640 non-null  bool
 33  Give_Way               226640 non-null  bool
 34  Junction               226640 non-null  bool
 35  No_Exit                226640 non-null  bool
 36  Railway                226640 non-null  bool
 37  Roundabout             226640 non-null  bool
 38  Station                226640 non-null  bool
 39  Stop                   226640 non-null  bool
 40  Traffic_Calming        226640 non-null  bool
 41  Traffic_Signal         226640 non-null  bool
 42  Turning_Loop           226640 non-null  bool
 43  Sunrise_Sunset         226640 non-null  object
 44  Civil_Twilight         226640 non-null  object
 45  Nautical_Twilight      226640 non-null  object
 46  Astronomical_Twilight  226640 non-null  object
dtypes: bool(13), float64(12), int64(1), object(21)
memory usage: 63.3+ MB

In [10]:
new['Number'].replace({"0": ""}, inplace=True)

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\series.py:4515: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [11]:
new = new.round(decimals=4)
new.reset_index(drop=True, inplace=True)
new.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-13,2,2018-04-19 12:48:57,2018-04-19 18:48:57,32.8669,-96.6662,32.8616,-96.6577,0.616,At Northwest Hwy/Exit 11 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-16,2,2019-04-11 16:35:14,2019-04-11 18:59:25,29.7233,-95.4973,29.7233,-95.4973,0.000,Accident on Westpark Dr at 14th St.,...,False,False,False,False,True,False,Day,Day,Day,Day
2,A-23,2,2018-02-15 10:59:40,2018-02-15 11:29:21,29.6405,-95.4824,29.6405,-95.4824,0.000,Accident on Chimney Rock Rd at US-90 Alt Main St.,...,False,False,False,False,True,False,Day,Day,Day,Day
3,A-28,2,2018-12-21 13:31:29,2018-12-21 14:01:20,30.4261,-97.7539,30.4261,-97.7539,0.000,Accident on Research Blvd Southbound at Pavili...,...,False,False,False,False,False,False,Day,Day,Day,Day
4,A-45,2,2020-01-06 15:37:19,2020-01-06 16:05:57,32.7584,-97.2576,32.7595,-97.2484,0.543,At Brentwood Stair Rd/Exit 19 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [12]:
Severity = []
i = 0
while i < len(new['Severity']):
    Severity.append(new['Severity'][i])
    i+=1

In [13]:
Start_Time = []
i = 0
while i < len(new['Start_Time']):
    Start_Time.append(new['Start_Time'][i])
    i+=1

In [14]:
Start_Lat = []
i = 0
while i < len(new['Start_Lat']):
    Start_Lat.append(new['Start_Lat'][i])
    i+=1

In [15]:
Start_Lng = []
i = 0
while i < len(new['Start_Lng']):
    Start_Lng.append(new['Start_Lng'][i])
    i+=1

In [16]:
City = []
i = 0
while i < len(new['City']):
    City.append(new['City'][i])
    i+=1

In [17]:
State = []
i = 0
while i < len(new['State']):
    State.append(new['State'][i])
    i+=1

In [18]:
Description = []
i = 0
while i < len(new['Description']):
    Description.append(new['Description'][i])
    i+=1

In [19]:
Street = []
i = 0
while i < len(new['Street']):
    Street.append(new['Street'][i])
    i+=1

In [20]:
Number = []
i = 0
while i < len(new['Number']):
    Number.append(new['Number'][i])
    i+=1

In [21]:
new['Description'][10]

'Accident on TX-261 Spur Shepherd Dr at Montgomery Rd.'

In [22]:
%%capture cap --no-stderr
for (a, b, c, d, e, f, g, h, i) in zip(Start_Time, Start_Lat, Start_Lng, Number, Street, City, State, Description, Severity):
    print(f'{{\n  datetime: "{a}",\n  address: "{d}{e}",\n  city: "{f}",\n  state: "{g}",\n  severity: "{i}",\n  location: "({b}, {c})",\n  description: "{h}"\n}},')

In [23]:
# Print to txt file
with open('TX_all_accidents_data.txt', 'w', encoding='UTF-8') as f:
    f.write(cap.stdout)

In [ ]:
new.info()

In [ ]:
def data2geojson(new):
    features = []
    insert_features = lambda X: features.append(
            geojson.Feature(geometry=geojson.Point((X["Start_Lng"],
                                                    X["Start_Lat"])),
                            properties=dict(datetime=X["Start_Time"],
                                            severity=X["Severity"],
                                            city=X["City"],
                                            state=X["State"],
                                            description=X["Description"])))
    new.apply(insert_features, axis=1)
    with open('TX_sev1_accidents.geojson', 'w', encoding='utf8') as fp:
        geojson.dump(geojson.FeatureCollection(features), fp, sort_keys=True, ensure_ascii=False)


data2geojson(new)