In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('../US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data_dropped = accidents_data[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'State', 'Number', 'Street', 'Description']]
accidents_data_dropped.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [4]:
accidents_data_dropped.rename(columns={"Start_Time": "Date/Time", "Start_Lat": "Latitude", "Start_Lng": "Longitude"}, errors="raise", inplace=True)
accidents_data_dropped.head()

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [5]:
arkansas_df = accidents_data_dropped.loc[accidents_data_dropped['State'] == "AR"]
arkansas_df

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
793,2,2020-10-28 09:03:30.000000000,34.908939,-91.196554,Brinkley,AR,NaN,I-40 W,Stationary traffic on I-40 from US-49/AR-17/Ex...
912,2,2020-10-15 21:00:56,35.221835,-92.833131,Atkins,AR,NaN,I-40 W,Incident on I-40 WB near I-40 Left lane blocked.
1190,2,2020-11-09 16:48:15,33.822199,-91.471602,Tillar,AR,101.0,Highway 159 E,Incident on US-65 NB near US-65 Left lane bloc...
2192,2,2020-10-03 07:03:17,34.328472,-92.924313,Donaldson,AR,NaN,I-30 W,Incident on I-30 WB near I-30 Left shoulder cl...
2443,2,2020-11-24 00:07:40,35.252130,-92.387379,Greenbrier,AR,NaN,Blueberry Hill Ln,Incident on US-65 SB near STATE HWY-285 Road c...
...,...,...,...,...,...,...,...,...,...
2901886,2,2019-06-06 12:09:11,35.149560,-90.135120,West Memphis,AR,NaN,I-55 N,At Club Rd/Exit 4 - Accident. Left lane blocked.
2903138,2,2020-12-04 05:40:31,34.181846,-93.073114,Arkadelphia,AR,NaN,I-30 W,Incident on I-30 WB near I-30 Road closed. Tak...
2905383,2,2020-12-19 22:49:48,34.669374,-92.350911,Little Rock,AR,6598.0,Baseline Rd,Incident on BASELINE RD near OMAN RD Drive wit...
2905410,2,2020-12-22 05:48:04,35.082591,-92.326937,Conway,AR,1.0,Fern Ln,Incident on US-64 EB near STATE HWY-36 Road cl...
2905420,2,2019-06-23 09:59:09,34.804300,-91.884010,Lonoke,AR,NaN,I-40 W,At AR-31/Exit 175 - Accident. Right lane blocked.

In [6]:
arkansas_df = arkansas_df.round(decimals=4)
arkansas_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
793,2,2020-10-28 09:03:30.000000000,34.9089,-91.1966,Brinkley,AR,NaN,I-40 W,Stationary traffic on I-40 from US-49/AR-17/Ex...
912,2,2020-10-15 21:00:56,35.2218,-92.8331,Atkins,AR,NaN,I-40 W,Incident on I-40 WB near I-40 Left lane blocked.
1190,2,2020-11-09 16:48:15,33.8222,-91.4716,Tillar,AR,101.0,Highway 159 E,Incident on US-65 NB near US-65 Left lane bloc...
2192,2,2020-10-03 07:03:17,34.3285,-92.9243,Donaldson,AR,NaN,I-30 W,Incident on I-30 WB near I-30 Left shoulder cl...
2443,2,2020-11-24 00:07:40,35.2521,-92.3874,Greenbrier,AR,NaN,Blueberry Hill Ln,Incident on US-65 SB near STATE HWY-285 Road c...

In [7]:
arkansas_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4726 entries, 793 to 2905420
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Severity     4726 non-null   int64
 1   Date/Time    4726 non-null   object
 2   Latitude     4726 non-null   float64
 3   Longitude    4726 non-null   float64
 4   City         4726 non-null   object
 5   State        4726 non-null   object
 6   Number       1691 non-null   float64
 7   Street       4726 non-null   object
 8   Description  4726 non-null   object
dtypes: float64(3), int64(1), object(5)
memory usage: 369.2+ KB

In [8]:
arkansas_df['Number'] = arkansas_df['Number'].fillna(0)

In [9]:
arkansas_df['Number'] = arkansas_df['Number'].map("{:.0f}".format)

In [10]:
arkansas_df['Number'].replace({"0": ""}, inplace=True)

In [11]:
arkansas_df.to_csv('../State_csv_files/Arkansas.csv', encoding='UTF-8', index=False)