In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('../US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data_dropped = accidents_data[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'State', 'Number', 'Street', 'Description']]
accidents_data_dropped.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [4]:
accidents_data_dropped.rename(columns={"Start_Time": "Date/Time", "Start_Lat": "Latitude", "Start_Lng": "Longitude"}, errors="raise", inplace=True)
accidents_data_dropped.head()

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [5]:
idaho_df = accidents_data_dropped.loc[accidents_data_dropped['State'] == "ID"]
idaho_df

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
808,2,2018-04-25 22:54:20,43.658890,-116.657000,Caldwell,ID,NaN,Vietnam Veterans Memorial Hwy,At ID-55/Exit 33 - Accident.
817,2,2020-12-09 01:30:15,43.594297,-116.448243,Meridian,ID,NaN,I-84 W,Incident on I-84 WB near TEN MILE RD Drive wit...
1392,2,2016-09-09 01:23:44,43.597051,-116.294968,Boise,ID,NaN,Vietnam Veterans Memorial Hwy,At I-184 - Accident.
1866,2,2020-10-12 13:28:00,43.633822,-116.354430,Meridian,ID,NaN,E Ustick Rd,Stationary traffic on ID-55 from E Ustick Rd (...
2368,2,2020-11-23 15:36:22,42.568639,-113.823328,Heyburn,ID,NaN,I-84 E,Incident on I-84 EB near ID-25 Drive with caut...
...,...,...,...,...,...,...,...,...,...
2905193,2,2018-07-06 12:42:24,43.368140,-114.267197,Bellevue,ID,10597.0,Highway 75,At Cedar St - Accident.
2905362,2,2020-12-11 19:48:15,43.607449,-116.274298,Boise,ID,NaN,I-184 W,Incident on I-184 WB near CURTIS RD Drive with...
2905655,4,2016-08-14 23:05:03,48.180980,-116.994270,Oldtown,ID,2401.0,E Highway 2,Closed at ID-57/NF-6/9th St - Road closed due ...
2905718,2,2020-09-15 15:30:24,43.691233,-116.356162,Eagle,ID,272.0,Highway 44,Incident on ID-44 WB near ID-55 Expect long de...
2905768,3,2017-02-24 17:46:53,43.598858,-116.490429,Nampa,ID,NaN,Vietnam Veterans Memorial Hwy,At Ten Mile Rd - Accident.

In [6]:
idaho_df = idaho_df.round(decimals=4)
idaho_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
808,2,2018-04-25 22:54:20,43.6589,-116.6570,Caldwell,ID,NaN,Vietnam Veterans Memorial Hwy,At ID-55/Exit 33 - Accident.
817,2,2020-12-09 01:30:15,43.5943,-116.4482,Meridian,ID,NaN,I-84 W,Incident on I-84 WB near TEN MILE RD Drive wit...
1392,2,2016-09-09 01:23:44,43.5971,-116.2950,Boise,ID,NaN,Vietnam Veterans Memorial Hwy,At I-184 - Accident.
1866,2,2020-10-12 13:28:00,43.6338,-116.3544,Meridian,ID,NaN,E Ustick Rd,Stationary traffic on ID-55 from E Ustick Rd (...
2368,2,2020-11-23 15:36:22,42.5686,-113.8233,Heyburn,ID,NaN,I-84 E,Incident on I-84 EB near ID-25 Drive with caut...

In [7]:
idaho_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4165 entries, 808 to 2905768
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Severity     4165 non-null   int64
 1   Date/Time    4165 non-null   object
 2   Latitude     4165 non-null   float64
 3   Longitude    4165 non-null   float64
 4   City         4165 non-null   object
 5   State        4165 non-null   object
 6   Number       1594 non-null   float64
 7   Street       4165 non-null   object
 8   Description  4165 non-null   object
dtypes: float64(3), int64(1), object(5)
memory usage: 325.4+ KB

In [8]:
idaho_df['Number'] = idaho_df['Number'].fillna(0)

In [9]:
idaho_df['Number'] = idaho_df['Number'].map("{:.0f}".format)

In [10]:
idaho_df['Number'].replace({"0": ""}, inplace=True)

In [11]:
idaho_df.to_csv('../State_csv_files/Idaho.csv', encoding='UTF-8', index=False)