In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import json
import geojson

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data['Severity'].value_counts()

2    2129263
3     629452
4     119144
1      28751
Name: Severity, dtype: int64

In [4]:
sample_df = accidents_data.sample(n=1000)

In [5]:
sample_df.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
1814087,A-1814088,2,2018-08-12 21:06:41,2018-08-12 21:36:14,35.841045,-78.611794,35.841045,-78.611794,0.000,Accident on Wake Forest Rd at Falls of Neuse Rd.,...,False,False,False,False,True,False,Night,Night,Day,Day
155010,A-155011,3,2016-07-21 16:24:58,2016-07-21 22:24:58,42.239620,-88.000370,42.254770,-88.020430,1.466,At IL-63/Midlothian Rd - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
2181071,A-2181072,2,2018-11-23 09:14:19,2018-11-23 09:43:42,47.542450,-122.304190,47.551750,-122.316660,0.867,Between Albro Pl/Swift Ave/Exit 161 and Corson...,...,False,False,False,False,False,False,Day,Day,Day,Day
2046389,A-2046390,2,2020-01-17 15:08:00,2020-01-17 15:42:20,44.951360,-93.025220,44.951360,-93.025220,0.000,At White Bear Ave/Exit 245 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2021493,A-2021494,2,2019-03-19 08:59:05,2019-03-19 09:58:39,39.265755,-76.666931,39.265755,-76.666931,0.000,Left hand shoulder blocked due to accident on ...,...,False,False,False,False,False,False,Day,Day,Day,Day

In [6]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1814087 to 2325583
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     1000 non-null   object
 1   Severity               1000 non-null   int64
 2   Start_Time             1000 non-null   object
 3   End_Time               1000 non-null   object
 4   Start_Lat              1000 non-null   float64
 5   Start_Lng              1000 non-null   float64
 6   End_Lat                898 non-null    float64
 7   End_Lng                898 non-null    float64
 8   Distance(mi)           1000 non-null   float64
 9   Description            1000 non-null   object
 10  Number                 355 non-null    float64
 11  Street                 1000 non-null   object
 12  Side                   1000 non-null   object
 13  City                   1000 non-null   object
 14  County                 1000 non-null   object
 15  State                  1000 non-null   object
 16  Zipcode                1000 non-null   object
 17  Country                1000 non-null   object
 18  Timezone               1000 non-null   object
 19  Airport_Code           997 non-null    object
 20  Weather_Timestamp      987 non-null    object
 21  Temperature(F)         985 non-null    float64
 22  Wind_Chill(F)          589 non-null    float64
 23  Humidity(%)            983 non-null    float64
 24  Pressure(in)           983 non-null    float64
 25  Visibility(mi)         978 non-null    float64
 26  Wind_Direction         984 non-null    object
 27  Wind_Speed(mph)        904 non-null    float64
 28  Precipitation(in)      548 non-null    float64
 29  Weather_Condition      977 non-null    object
 30  Amenity                1000 non-null   bool
 31  Bump                   1000 non-null   bool
 32  Crossing               1000 non-null   bool
 33  Give_Way               1000 non-null   bool
 34  Junction               1000 non-null   bool
 35  No_Exit                1000 non-null   bool
 36  Railway                1000 non-null   bool
 37  Roundabout             1000 non-null   bool
 38  Station                1000 non-null   bool
 39  Stop                   1000 non-null   bool
 40  Traffic_Calming        1000 non-null   bool
 41  Traffic_Signal         1000 non-null   bool
 42  Turning_Loop           1000 non-null   bool
 43  Sunrise_Sunset         1000 non-null   object
 44  Civil_Twilight         1000 non-null   object
 45  Nautical_Twilight      1000 non-null   object
 46  Astronomical_Twilight  1000 non-null   object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 286.1+ KB

In [ ]:
# new = accidents_data.loc[(accidents_data['Severity'] == 1)]
# new.head()

In [ ]:
accidents_data = accidents_data.round(decimals=4)
accidents_data.head()

In [ ]:
accidents_data.info()

In [ ]:
empty = new.loc[new['City'] == "NaN"]
empty

# null_columns = new.columns[new.isnull().any()]
# new[null_columns].isnull().sum

In [ ]:
accidents_data=accidents_data[accidents_data['City'].notna()]
accidents_data.head()

In [ ]:
new_df.info()

In [ ]:
print(new[new['City'].isnull()][null_columns])

In [ ]:
new.info()

In [7]:
def data2geojson(sample_df):
    features = []
    insert_features = lambda X: features.append(
            geojson.Feature(geometry=geojson.Point((X["Start_Lng"],
                                                    X["Start_Lat"])),
                            properties=dict(datetime=X["Start_Time"],
                                            severity=X["Severity"],
                                            city=X["City"],
                                            state=X["State"],
                                            description=X["Description"])))
    sample_df.apply(insert_features, axis=1)
    with open('USA_all_accidents_sample.geojson', 'w', encoding='utf8') as fp:
        geojson.dump(geojson.FeatureCollection(features), fp, sort_keys=True, ensure_ascii=False)


data2geojson(sample_df)

In [12]:
sample_df

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
1814087,A-1814088,2,2018-08-12 21:06:41,2018-08-12 21:36:14,35.841045,-78.611794,35.841045,-78.611794,0.000,Accident on Wake Forest Rd at Falls of Neuse Rd.,...,False,False,False,False,True,False,Night,Night,Day,Day
155010,A-155011,3,2016-07-21 16:24:58,2016-07-21 22:24:58,42.239620,-88.000370,42.254770,-88.020430,1.466,At IL-63/Midlothian Rd - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
2181071,A-2181072,2,2018-11-23 09:14:19,2018-11-23 09:43:42,47.542450,-122.304190,47.551750,-122.316660,0.867,Between Albro Pl/Swift Ave/Exit 161 and Corson...,...,False,False,False,False,False,False,Day,Day,Day,Day
2046389,A-2046390,2,2020-01-17 15:08:00,2020-01-17 15:42:20,44.951360,-93.025220,44.951360,-93.025220,0.000,At White Bear Ave/Exit 245 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
2021493,A-2021494,2,2019-03-19 08:59:05,2019-03-19 09:58:39,39.265755,-76.666931,39.265755,-76.666931,0.000,Left hand shoulder blocked due to accident on ...,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2087502,A-2087503,2,2017-07-24 08:36:32,2017-07-24 14:36:32,35.211740,-80.857690,35.211740,-80.857690,0.000,At South Blvd - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
1110596,A-1110597,2,2020-04-08 16:51:55,2020-04-08 17:26:53,38.877800,-76.962020,38.877800,-76.962020,0.000,At Randle Cir SE/Minnesota Ave SE - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1090061,A-1090062,3,2019-05-27 13:52:23,2019-05-27 14:36:51,40.690189,-73.999603,40.690189,-73.999603,0.000,Left and center lane blocked due to accident o...,...,False,False,False,False,False,False,Day,Day,Day,Day
70086,A-70087,2,2019-07-10 05:02:13,2019-07-10 06:34:23,37.941082,-122.324280,37.941082,-122.324280,0.000,Right hand shoulder blocked due to accident on...,...,False,False,False,False,False,False,Night,Night,Day,Day
2325583,A-2325584,2,2020-12-13 23:42:07,2020-12-14 00:49:32,30.255779,-81.601177,30.244509,-81.589367,1.050,Stationary traffic on I-95 S from Bowden Rd/Ex...,...,False,False,False,False,False,False,Night,Night,Night,Night

In [14]:
sample_df.to_csv('sample_df.csv')