In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('../US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data_dropped = accidents_data[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'State', 'Number', 'Street', 'Description']]
accidents_data_dropped.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [4]:
accidents_data_dropped.rename(columns={"Start_Time": "Date/Time", "Start_Lat": "Latitude", "Start_Lng": "Longitude"}, errors="raise", inplace=True)
accidents_data_dropped.head()

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [5]:
connecticut_df = accidents_data_dropped.loc[accidents_data_dropped['State'] == "CT"]
connecticut_df

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
74,2,2016-10-15 15:57:26,41.755451,-72.650444,East Hartford,CT,NaN,Wilbur Cross Hwy N,Slow traffic and left lane closed due to accid...
170,3,2019-02-02 17:00:20,41.177315,-73.173042,Bridgeport,CT,NaN,Governor John Davis Lodge Tpke,Right lane blocked due to accident on I-95 Gov...
177,3,2020-01-22 15:29:39,41.272640,-72.970589,West Haven,CT,NaN,Governor John Davis Lodge Tpke N,Right lane blocked due to accident on I-95 Gov...
260,2,2020-12-24 07:53:00,41.580649,-72.899661,Plantsville,CT,NaN,I-84 E,Stationary traffic on I-84 E from CT-10/Exit 2...
298,2,2020-12-30 17:22:00,41.171610,-73.191683,Bridgeport,CT,436.0,Warren St,Stationary traffic on I-95 S - Governor John D...
...,...,...,...,...,...,...,...,...,...
2905596,2,2020-09-28 21:55:14,41.761723,-72.697322,Hartford,CT,NaN,I-84 E,Slow traffic on I-84 from Flatbush Ave/Exit 45...
2905912,2,2020-09-11 03:01:00,41.494470,-73.160737,Southbury,CT,NaN,I-84 E,Incident on I-84 EB near EXIT 16 Road closed. ...
2906208,2,2016-12-13 10:17:44,41.737210,-72.740150,West Hartford,CT,NaN,US-6 W,Between Main Street/Exit 41 and CT-71/New Brit...
2906454,3,2019-12-19 08:37:14,41.233234,-73.069374,Milford,CT,NaN,I-95 S,Left lane blocked due to accident on I-95 Gove...
2906487,3,2017-04-28 20:34:21,41.763977,-72.693848,Hartford,CT,NaN,Sigourney St,Accident on I-84 Westbound after Exit 47 Sigou...

In [6]:
connecticut_df = connecticut_df.round(decimals=4)
connecticut_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
74,2,2016-10-15 15:57:26,41.7555,-72.6504,East Hartford,CT,NaN,Wilbur Cross Hwy N,Slow traffic and left lane closed due to accid...
170,3,2019-02-02 17:00:20,41.1773,-73.1730,Bridgeport,CT,NaN,Governor John Davis Lodge Tpke,Right lane blocked due to accident on I-95 Gov...
177,3,2020-01-22 15:29:39,41.2726,-72.9706,West Haven,CT,NaN,Governor John Davis Lodge Tpke N,Right lane blocked due to accident on I-95 Gov...
260,2,2020-12-24 07:53:00,41.5806,-72.8997,Plantsville,CT,NaN,I-84 E,Stationary traffic on I-84 E from CT-10/Exit 2...
298,2,2020-12-30 17:22:00,41.1716,-73.1917,Bridgeport,CT,436.0,Warren St,Stationary traffic on I-95 S - Governor John D...

In [7]:
connecticut_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24054 entries, 74 to 2906487
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Severity     24054 non-null  int64
 1   Date/Time    24054 non-null  object
 2   Latitude     24054 non-null  float64
 3   Longitude    24054 non-null  float64
 4   City         24054 non-null  object
 5   State        24054 non-null  object
 6   Number       4100 non-null   float64
 7   Street       24054 non-null  object
 8   Description  24054 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 1.8+ MB

In [8]:
connecticut_df['Number'] = connecticut_df['Number'].fillna(0)

In [9]:
connecticut_df['Number'] = connecticut_df['Number'].map("{:.0f}".format)

In [10]:
connecticut_df['Number'].replace({"0": ""}, inplace=True)

In [11]:
connecticut_df.to_csv('../State_csv_files/Connecticut.csv', encoding='UTF-8', index=False)