In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('../US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data_dropped = accidents_data[['Severity', 'Start_Time', 'Start_Lat', 'Start_Lng', 'City', 'State', 'Number', 'Street', 'Description']]
accidents_data_dropped.head()

,Severity,Start_Time,Start_Lat,Start_Lng,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [4]:
accidents_data_dropped.rename(columns={"Start_Time": "Date/Time", "Start_Lat": "Latitude", "Start_Lng": "Longitude"}, errors="raise", inplace=True)
accidents_data_dropped.head()

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
0,2,2019-05-21 08:29:55,34.808868,-82.269157,Greenville,SC,439.0,Tanner Rd,Accident on Tanner Rd at Pennbrooke Ln.
1,2,2019-10-07 17:43:09,35.090080,-80.745560,Charlotte,NC,3299.0,Providence Branch Ln,Accident on Houston Branch Rd at Providence Br...
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
3,2,2018-04-17 16:51:23,39.110390,-119.773781,Carson City,NV,NaN,US Highway 395 S,Accident on US-395 Southbound at Topsy Ln.
4,3,2016-08-31 17:40:49,26.102942,-80.265091,Fort Lauderdale,FL,NaN,I-595 W,Accident on I-595 Westbound at Exit 4 / Pine I...

In [5]:
california_df = accidents_data_dropped.loc[accidents_data_dropped['State'] == "CA"]
california_df

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
2,2,2020-12-13 21:53:00,37.145730,-121.985052,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
7,2,2019-12-21 23:59:00,34.034017,-118.026972,Whittier,CA,NaN,CA-60 W,At CA-60/Pomona Fwy - Accident.
9,2,2019-01-30 08:44:18,34.426330,-118.585100,Valencia,CA,NaN,Golden State Fwy S,At Magic Mountain Pky - Accident. Hard shoulde...
16,2,2016-07-09 14:54:01,34.103172,-118.249969,Los Angeles,CA,NaN,CA-2 S,Accident on CA-2 Southbound at Exit 13 I-5.
17,2,2020-11-21 16:32:00,34.186595,-117.439427,Fontana,CA,3738.0,Sierra Ave,Incident on SIERRA AVE near LYTLE CREEK RD Exp...
...,...,...,...,...,...,...,...,...,...
2906586,2,2019-10-25 08:00:41,33.981899,-118.191948,Bell Gardens,CA,4198.0,Randolph St,Accident on Randolph St at Otis Ave.
2906589,3,2017-08-24 07:53:55,34.231285,-118.266190,La Crescenta,CA,NaN,Foothill Fwy W,Accident on I-210 Eastbound at Lowell Ave.
2906590,3,2018-04-18 17:16:44,37.676400,-122.109800,Hayward,CA,NaN,Meekland Ave,At Meekland Ave - Accident.
2906599,2,2020-02-24 11:34:00,33.888992,-118.188797,Compton,CA,NaN,E Alondra Blvd,At Alondra Blvd - Accident.
2906606,2,2019-01-10 02:01:01,34.068890,-117.342010,Colton,CA,NaN,Cypress Ave,At Valley Blvd - Accident.

In [6]:
california_df = california_df.round(decimals=4)
california_df.head()

,Severity,Date/Time,Latitude,Longitude,City,State,Number,Street,Description
2,2,2020-12-13 21:53:00,37.1457,-121.9851,Los Gatos,CA,NaN,Santa Cruz Hwy,Stationary traffic on CA-17 from Summit Rd (CA...
7,2,2019-12-21 23:59:00,34.0340,-118.0270,Whittier,CA,NaN,CA-60 W,At CA-60/Pomona Fwy - Accident.
9,2,2019-01-30 08:44:18,34.4263,-118.5851,Valencia,CA,NaN,Golden State Fwy S,At Magic Mountain Pky - Accident. Hard shoulde...
16,2,2016-07-09 14:54:01,34.1032,-118.2500,Los Angeles,CA,NaN,CA-2 S,Accident on CA-2 Southbound at Exit 13 I-5.
17,2,2020-11-21 16:32:00,34.1866,-117.4394,Fontana,CA,3738.0,Sierra Ave,Incident on SIERRA AVE near LYTLE CREEK RD Exp...

In [7]:
california_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730744 entries, 2 to 2906606
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Severity     730744 non-null  int64
 1   Date/Time    730744 non-null  object
 2   Latitude     730744 non-null  float64
 3   Longitude    730744 non-null  float64
 4   City         730738 non-null  object
 5   State        730744 non-null  object
 6   Number       170498 non-null  float64
 7   Street       730744 non-null  object
 8   Description  730744 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 55.8+ MB

In [8]:
california_df['Number'] = california_df['Number'].fillna(0)

In [9]:
california_df['Number'] = california_df['Number'].map("{:.0f}".format)

In [10]:
california_df['Number'].replace({"0": ""}, inplace=True)

In [11]:
california_df.to_csv('../State_csv_files/California.csv', encoding='UTF-8', index=False)