In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import json
import geojson

In [2]:
# Read the accidents CSV into Pandas DataFrame
accidents_data = pd.read_csv('US_Accidents_Dec20_Updated.csv')
accidents_data.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,2,2019-05-21 08:29:55,2019-05-21 09:29:40,34.808868,-82.269157,34.808868,-82.269157,0.0,Accident on Tanner Rd at Pennbrooke Ln.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-2,2,2019-10-07 17:43:09,2019-10-07 19:42:50,35.090080,-80.745560,35.090080,-80.745560,0.0,Accident on Houston Branch Rd at Providence Br...,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-3,2,2020-12-13 21:53:00,2020-12-13 22:44:00,37.145730,-121.985052,37.165850,-121.988062,1.4,Stationary traffic on CA-17 from Summit Rd (CA...,...,False,False,False,False,False,False,Night,Night,Night,Night
3,A-4,2,2018-04-17 16:51:23,2018-04-17 17:50:46,39.110390,-119.773781,39.110390,-119.773781,0.0,Accident on US-395 Southbound at Topsy Ln.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-5,3,2016-08-31 17:40:49,2016-08-31 18:10:49,26.102942,-80.265091,26.102942,-80.265091,0.0,Accident on I-595 Westbound at Exit 4 / Pine I...,...,False,False,False,False,True,False,Day,Day,Day,Day

In [3]:
accidents_data['Severity'].value_counts()

2    2129263
3     629452
4     119144
1      28751
Name: Severity, dtype: int64

In [4]:
new = accidents_data.loc[(accidents_data['Severity'] == 1) & (accidents_data['State'] == 'TX')]
new

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
1119,A-1120,1,2020-04-14 17:46:14,2020-04-14 18:51:12,31.75875,-106.35586,31.75875,-106.35586,0.0,At I-10/Gateway Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1205,A-1206,1,2020-04-21 13:34:33,2020-04-21 14:19:33,31.70480,-106.31762,31.70480,-106.31762,0.0,At FM-76/North Loop Dr - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
5527,A-5528,1,2020-05-28 13:58:17,2020-05-28 14:33:15,31.77157,-106.37720,31.77157,-106.37720,0.0,At Hawkins Blvd/Exit 26 - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
6055,A-6056,1,2020-04-05 17:34:30,2020-04-05 18:34:30,31.74995,-106.32737,31.74995,-106.32737,0.0,At Pellicano Dr - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
7300,A-7301,1,2020-05-18 13:34:15,2020-05-18 14:19:15,31.75630,-106.35111,31.75630,-106.35111,0.0,At FM-2316/McRae Blvd/Exit 28A - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888662,A-2888663,1,2020-06-23 10:48:40,2020-06-23 11:53:38,31.75251,-106.34531,31.75251,-106.34531,0.0,At Yarbrough Dr/Exit 28B - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
2894867,A-2894868,1,2020-04-21 19:47:59,2020-04-21 20:32:59,31.78354,-106.24461,31.78354,-106.24461,0.0,At Pebble Hills Blvd - Accident.,...,False,False,False,False,True,False,Night,Day,Day,Day
2898829,A-2898830,1,2020-05-12 14:13:51,2020-05-12 14:58:51,31.92837,-106.40733,31.92837,-106.40733,0.0,At Sean Haggerty Dr - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
2899464,A-2899465,1,2020-06-06 18:49:13,2020-06-06 19:49:13,31.75608,-106.27410,31.75608,-106.27410,0.0,At Vista Del Sol Dr - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
2905328,A-2905329,1,2020-04-25 12:51:27,2020-04-25 13:56:25,31.89390,-106.41239,31.89390,-106.41239,0.0,At Diana Dr - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [5]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1004 entries, 1119 to 2905328
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     1004 non-null   object
 1   Severity               1004 non-null   int64
 2   Start_Time             1004 non-null   object
 3   End_Time               1004 non-null   object
 4   Start_Lat              1004 non-null   float64
 5   Start_Lng              1004 non-null   float64
 6   End_Lat                997 non-null    float64
 7   End_Lng                997 non-null    float64
 8   Distance(mi)           1004 non-null   float64
 9   Description            1004 non-null   object
 10  Number                 488 non-null    float64
 11  Street                 1004 non-null   object
 12  Side                   1004 non-null   object
 13  City                   1004 non-null   object
 14  County                 1004 non-null   object
 15  State                  1004 non-null   object
 16  Zipcode                1004 non-null   object
 17  Country                1004 non-null   object
 18  Timezone               1004 non-null   object
 19  Airport_Code           1004 non-null   object
 20  Weather_Timestamp      1004 non-null   object
 21  Temperature(F)         1004 non-null   float64
 22  Wind_Chill(F)          958 non-null    float64
 23  Humidity(%)            1004 non-null   float64
 24  Pressure(in)           1004 non-null   float64
 25  Visibility(mi)         1004 non-null   float64
 26  Wind_Direction         1003 non-null   object
 27  Wind_Speed(mph)        998 non-null    float64
 28  Precipitation(in)      176 non-null    float64
 29  Weather_Condition      1004 non-null   object
 30  Amenity                1004 non-null   bool
 31  Bump                   1004 non-null   bool
 32  Crossing               1004 non-null   bool
 33  Give_Way               1004 non-null   bool
 34  Junction               1004 non-null   bool
 35  No_Exit                1004 non-null   bool
 36  Railway                1004 non-null   bool
 37  Roundabout             1004 non-null   bool
 38  Station                1004 non-null   bool
 39  Stop                   1004 non-null   bool
 40  Traffic_Calming        1004 non-null   bool
 41  Traffic_Signal         1004 non-null   bool
 42  Turning_Loop           1004 non-null   bool
 43  Sunrise_Sunset         1004 non-null   object
 44  Civil_Twilight         1004 non-null   object
 45  Nautical_Twilight      1004 non-null   object
 46  Astronomical_Twilight  1004 non-null   object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 287.3+ KB

In [6]:
new['Number'] = new['Number'].fillna(0)

C:\Users\frost\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [8]:
new['Number'] = new['Number'].map("{:.0f}".format)
# pd.options.display.float_format = '{:,.0f}'.format
# df['C'] = df['C'].apply(np.int64)

C:\Users\frost\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1004 entries, 1119 to 2905328
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     1004 non-null   object
 1   Severity               1004 non-null   int64
 2   Start_Time             1004 non-null   object
 3   End_Time               1004 non-null   object
 4   Start_Lat              1004 non-null   float64
 5   Start_Lng              1004 non-null   float64
 6   End_Lat                997 non-null    float64
 7   End_Lng                997 non-null    float64
 8   Distance(mi)           1004 non-null   float64
 9   Description            1004 non-null   object
 10  Number                 1004 non-null   float64
 11  Street                 1004 non-null   object
 12  Side                   1004 non-null   object
 13  City                   1004 non-null   object
 14  County                 1004 non-null   object
 15  State                  1004 non-null   object
 16  Zipcode                1004 non-null   object
 17  Country                1004 non-null   object
 18  Timezone               1004 non-null   object
 19  Airport_Code           1004 non-null   object
 20  Weather_Timestamp      1004 non-null   object
 21  Temperature(F)         1004 non-null   float64
 22  Wind_Chill(F)          958 non-null    float64
 23  Humidity(%)            1004 non-null   float64
 24  Pressure(in)           1004 non-null   float64
 25  Visibility(mi)         1004 non-null   float64
 26  Wind_Direction         1003 non-null   object
 27  Wind_Speed(mph)        998 non-null    float64
 28  Precipitation(in)      176 non-null    float64
 29  Weather_Condition      1004 non-null   object
 30  Amenity                1004 non-null   bool
 31  Bump                   1004 non-null   bool
 32  Crossing               1004 non-null   bool
 33  Give_Way               1004 non-null   bool
 34  Junction               1004 non-null   bool
 35  No_Exit                1004 non-null   bool
 36  Railway                1004 non-null   bool
 37  Roundabout             1004 non-null   bool
 38  Station                1004 non-null   bool
 39  Stop                   1004 non-null   bool
 40  Traffic_Calming        1004 non-null   bool
 41  Traffic_Signal         1004 non-null   bool
 42  Turning_Loop           1004 non-null   bool
 43  Sunrise_Sunset         1004 non-null   object
 44  Civil_Twilight         1004 non-null   object
 45  Nautical_Twilight      1004 non-null   object
 46  Astronomical_Twilight  1004 non-null   object
dtypes: bool(13), float64(13), int64(1), object(20)
memory usage: 287.3+ KB

In [9]:
new['Number'].replace({"0": ""}, inplace=True)

C:\Users\frost\anaconda3\envs\PythonData\lib\site-packages\pandas\core\series.py:4515: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [10]:
new = new.round(decimals=4)
new.reset_index(drop=True, inplace=True)
new.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1120,1,2020-04-14 17:46:14,2020-04-14 18:51:12,31.7588,-106.3559,31.7588,-106.3559,0.0,At I-10/Gateway Blvd - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day
1,A-1206,1,2020-04-21 13:34:33,2020-04-21 14:19:33,31.7048,-106.3176,31.7048,-106.3176,0.0,At FM-76/North Loop Dr - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
2,A-5528,1,2020-05-28 13:58:17,2020-05-28 14:33:15,31.7716,-106.3772,31.7716,-106.3772,0.0,At Hawkins Blvd/Exit 26 - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
3,A-6056,1,2020-04-05 17:34:30,2020-04-05 18:34:30,31.7500,-106.3274,31.7500,-106.3274,0.0,At Pellicano Dr - Accident.,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-7301,1,2020-05-18 13:34:15,2020-05-18 14:19:15,31.7563,-106.3511,31.7563,-106.3511,0.0,At FM-2316/McRae Blvd/Exit 28A - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [11]:
Severity = []
i = 0
while i < len(new['Severity']):
    Severity.append(new['Severity'][i])
    i+=1

In [12]:
Start_Time = []
i = 0
while i < len(new['Start_Time']):
    Start_Time.append(new['Start_Time'][i])
    i+=1

In [13]:
Start_Lat = []
i = 0
while i < len(new['Start_Lat']):
    Start_Lat.append(new['Start_Lat'][i])
    i+=1

In [14]:
Start_Lng = []
i = 0
while i < len(new['Start_Lng']):
    Start_Lng.append(new['Start_Lng'][i])
    i+=1

In [15]:
City = []
i = 0
while i < len(new['City']):
    City.append(new['City'][i])
    i+=1

In [16]:
State = []
i = 0
while i < len(new['State']):
    State.append(new['State'][i])
    i+=1

In [17]:
Description = []
i = 0
while i < len(new['Description']):
    Description.append(new['Description'][i])
    i+=1

In [18]:
Street = []
i = 0
while i < len(new['Street']):
    Street.append(new['Street'][i])
    i+=1

In [19]:
Number = []
i = 0
while i < len(new['Number']):
    Number.append(new['Number'][i])
    i+=1

In [20]:
new['Description'][10]

'At Vista Del Sol Dr - Accident.'

In [43]:
%%capture cap --no-stderr
for (a, b, c, d, e, f, g, h, i) in zip(Start_Time, Start_Lat, Start_Lng, Number, Street, City, State, Description, Severity):
    print(f'{{\n  datetime: "{a}",\n  address: "{d} {e}",\n  city: "{f}",\n  state: "{g}",\n  severity: "{i}",\n  location: "({b}, {c})",\n  description: "{h}"\n}},')

In [44]:
# Print to txt file
with open('TX_sev1_accidents_data.txt', 'w', encoding='UTF-8') as f:
    f.write(cap.stdout)

In [ ]:
new.info()

In [ ]:
def data2geojson(new):
    features = []
    insert_features = lambda X: features.append(
            geojson.Feature(geometry=geojson.Point((X["Start_Lng"],
                                                    X["Start_Lat"])),
                            properties=dict(datetime=X["Start_Time"],
                                            severity=X["Severity"],
                                            city=X["City"],
                                            state=X["State"],
                                            description=X["Description"])))
    new.apply(insert_features, axis=1)
    with open('TX_sev1_accidents.geojson', 'w', encoding='utf8') as fp:
        geojson.dump(geojson.FeatureCollection(features), fp, sort_keys=True, ensure_ascii=False)


data2geojson(new)